## Question 1

Write a python program to multiply  a M * N matrix by N * A matrix and create a real matrix product.

Importing All libraries

In [1]:
# Importing pandas for data formatting 
# Importing numy for numerical calculations
import pandas as pd 
import numpy as np


In [2]:
M=int(input('Enter the value of M'))# Taking input from user
N=int(input('Enter the value of N'))# Taking input from user
A=int(input('Enter the value of A'))# Taking input from user

# Printing values of M,N,A
print('Value of M',M)
print('Value of N',N)
print('Value of A',A)

Matrix_of_m_and_N=np.random.rand(M,N) # Creating a Numpy 2-dimenstional matrix of size M*N
# printing Matrix
print("First Array\n",Matrix_of_m_and_N,"\n")
# printing type of our matrix size M*N
print(type(Matrix_of_m_and_N))
# As we already know that matrix is nothing but a combination of n-dimentions arrays.
Matrix_of_n_and_a=np.random.rand(N,A)# Creating a Numpy 2-dimenstional matrix of size N*A
 #printing Matrix
print("Second array\n",Matrix_of_n_and_a,"\n")

print("Dot Product of two arrays")
np.dot(Matrix_of_m_and_N,Matrix_of_n_and_a)



Value of M 2
Value of N 2
Value of A 2
First Array
 [[0.14793372 0.64923286]
 [0.51652686 0.09129709]] 

<class 'numpy.ndarray'>
Second array
 [[0.36331661 0.52291222]
 [0.32159721 0.8743209 ]] 

Dot Product of two arrays


array([[0.26253825, 0.64499421],
       [0.21702368, 0.34992116]])

## Question 2

Write a numPy program to check if each elements of array of your is composed of digits, lowercase letters and upper case letters only.


In [3]:
n=['machine','PowerBi','data','Neural','16','learing','STUDY']#Creating a list of values to check
n

['machine', 'PowerBi', 'data', 'Neural', '16', 'learing', 'STUDY']

In [4]:
digitonlylist=[]
for i in n:
    digitonlylist=digitonlylist+[i.isdigit()]
print("Digit only",digitonlylist)    

Digit only [False, False, False, False, True, False, False]


In [5]:
upperonlylist=[]
for i in n:
    upperonlylist=upperonlylist+[i.isupper()]
print("upper only",upperonlylist)    

upper only [False, False, False, False, False, False, True]


In [6]:
loweronlylist=[]
for i in n:
    loweronlylist=loweronlylist+[i.islower()]
print("lower only",loweronlylist)  

lower only [True, False, True, False, False, True, False]


## Question 3

Write a program thatreads two space-separated positive integers 푋and 푌as input and perform the following tasks

In [7]:
x,y=map(int,input("Enter a Space seprated integer value").split())
print(x)
print(y)


ValueError: not enough values to unpack (expected 2, got 1)

Create a list (lst1) starting at one (1) with 16 elements at a step of X

In [ ]:
lst1=np.arange(1,16*x,x)
lst1=lst1.tolist()
print("Printing List lst1",lst1)

Printing List lst1 [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31]


Create a list (lst2) starting at one (1) with 16 elements at a step of Y

In [ ]:
lst2=np.arange(1,16*y,y)
lst2=lst2.tolist()
lst2
print("Printing List lst2",lst2)

Printing List lst [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46]


Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively 

In [ ]:
np1=np.array(lst1)
np2=np.array(lst2)
print("Printing numpy array made using lst2 and lst2\n",np1,"\n", np2)

Printing numpy array made using lst2 and lst2
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31] 
 [ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46]


Reshape both the NumPy arrays to (4,4)

In [ ]:
np1=np1.reshape(4,4)
np2=np2.reshape(4,4)
print("Printting both rehaped (4,4) array\n",np1,"\n\n",np2)

Printting both rehaped (4,4) array
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]] 

 [[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]
 [37 40 43 46]]


Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -np2)

In [ ]:
np1_np2_sub=np.subtract(np1,np2)
np1_np2_sub

array([[  0,  -1,  -2,  -3],
       [ -4,  -5,  -6,  -7],
       [ -8,  -9, -10, -11],
       [-12, -13, -14, -15]])

In [ ]:
print("printing reshaped (1 dimentional) subtracted array\n",np1_np2_sub.ravel())

printing reshaped (1 dimentional) subtracted array
 [  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15]


## Question 4

Write a Python program thattakes two integer-NumPy arrays, P and Q of shape [3∗3]and perform the following task


In [ ]:
p=np.array(range(0,9))# creating a 9 elemets array
q=np.array(range(10,19))# creating a 9 elemets array
p,q

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18]))

In [ ]:
p=p.reshape(3,3)# reshapping the array into a 3,3 matrix
q=q.reshape(3,3)

In [ ]:
nsub=np.subtract(p,q)# subtracting array
print("Printing subtracted array of size (3,3\n",nsub)

Printing subtracted array of size (3,3
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]
